services:
    exs_campaigner.manager_configurator:
        class: 'EXS\CampaignerBundle\Service\XsdPathConfigurator'
        public: false
        arguments:
            - '@file_locator'
            - '%exs_campaigner.xsd.contact_search_criteria%'

    exs_campaigner.contact_manager:
        class: 'EXS\CampaignerBundle\Service\ContactManager'
        configurator: ['@exs_campaigner.manager_configurator', 'configure']
        arguments:
            - '%exs_campaigner.wsdl.contact_management%'
            - '%exs_campaigner.username%'
            - '%exs_campaigner.password%'

    exs_campaigner.campaign_manager:
        class: 'EXS\CampaignerBundle\Service\CampaignManager'
        arguments:
            - '%exs_campaigner.wsdl.campaign_management%'
            - '%exs_campaigner.username%'
            - '%exs_campaigner.password%'

    exs_campaigner.list_manager:
        class: 'EXS\CampaignerBundle\Service\ListManager'
        configurator: ['@exs_campaigner.manager_configurator', 'configure']
        arguments:
            - '%exs_campaigner.wsdl.list_management%'
            - '%exs_campaigner.username%'
            - '%exs_campaigner.password%'

    exs_campaigner.content_management:
        class: 'EXS\CampaignerBundle\Service\ContentManager'
        arguments:
            - '%exs_campaigner.wsdl.list_management%'
            - '%exs_campaigner.username%'
            - '%exs_campaigner.password%'

    exs_campaigner.workflow_management:
        class: 'EXS\CampaignerBundle\Service\WorkflowManager'
        configurator: ['@exs_campaigner.manager_configurator', 'configure']
        arguments:
            - '%exs_campaigner.wsdl.list_management%'
            - '%exs_campaigner.username%'
            - '%exs_campaigner.password%'
